### PR TITLE
feat: make intgration request and update integration request added in to utils file

### PR DESCRIPTION
**Pull request by vishdha**
description: feat: make intgration request and update integration request added in to utils file

### CODE REVIEW

**Review by sahil28297 — DISMISSED** [review]

**Comment by sahil28297** [comment]
@vishdha why is this in hotfix branch? rebase it to oct-sprint-1 branch

**Comment by vishdha** [comment]
> @vishdha why is this in hotfix branch? rebase it to oct-sprint-1 branch

when it will deploy on develop then?

**Comment by sahil28297** [comment]
> > @vishdha why is this in hotfix branch? rebase it to oct-sprint-1 branch
> 
> when it will deploy on develop then?
On which branch do you need this code and when?

once we release the taxjar_integration branch which is created from develop

currently my frappe branch: develop and erpnext branch: taxjar_intgration created from develop

**Comment by vishdha** [comment]
Closing this added new PR https://github.com/Bloomstack/frappe/pull/794

**Pull request closed without merging**
