### PR TITLE
[v13] pull fixes from upstream

### PR DESCRIPTION
**Pull request by vishdha**
TASK ID: [ASANA](https://app.asana.com/0/1198992588740629/1198992588764632)
Changes: 
[feat: add sidebar items to navbar in mobile](https://github.com/frappe/frappe/pull/9941)

### CODE REVIEW

**Comment by hrwX** [comment]
- @vishdha Raise separate PR for each feature.
- Also skip the backup one since we use mariadb directly for backing up here.

**Comment by vishdha** [comment]
@hrwX Added separate PRs

**Comment by hrwX** [comment]
@vishdha Where are the file changes ?

**Comment by vishdha** [comment]
changes already pull from develop

**Pull request closed without merging**
