### PR TITLE
fix(text-editor): List UI

### PR DESCRIPTION
**Pull request by Alchez**
**Ref:** [TASK-2020-01090](https://bloomstack.com/desk#Form/Task/TASK-2020-01090)

Pulled from [upstream PR](https://github.com/frappe/frappe/pull/10598).

### CODE REVIEW

**Comment by DeveloperMetal** [comment]
@Alchez were you able to test if this fixes the text editor issues?

**Comment by Alchez** [comment]
@DeveloperMetal, I just tested it out, and the list numbering is working for me

image

I'm trying some edits now to allow font resizing as well.

**Comment by Alchez** [comment]
@DeveloperMetal, I was able to add some basic sizing options that Quill allows, but I'm having trouble with the API calls to actually change the font size. Let's have a quick chat on this when you're free next.

image

**Review by DeveloperMetal — APPROVED** [review]
Looking good. As discussed, we'll tackle the text sizing on another task

**Comment by Alchez** [comment]
Additional fix made at https://github.com/DigiThinkIT/frappe/pull/233.

**Pull request merged**
