### PR TITLE
fix(user): remove password update notification feature for security

### PR DESCRIPTION
**Pull request by vjFaLk**

### CODE REVIEW

**Comment by Alchez** [comment]
Can we not improve this, instead of removing it entirely?

**Comment by DeveloperMetal** [comment]
@Alchez The fact that its sending passwords plain text is awful. 
The right way to go about it is to email a reset password link, but I don't believe that's what this is. This is the notification when a password changes on the backend right @vjFaLk ? which should never happen

**Review by DeveloperMetal — APPROVED** [review]

**Comment by Alchez** [comment]
@forellana-digithinkit, yeah, the "Reset Password" feature already exists. Also, I agree that we should remove the 'set password from the backend' entirely, or restrict it for development setups.

@vjFaLk Just noting that you're not removing the "Set Password" field here.

**Comment by vjFaLk** [comment]
@Alchez Correct, we'll keep the ability to set a password manually for a User, however it's their job to securely communicate the password to the User 

@forellana-digithinkit Does that make sense, or should I remove that feature too? This helps sometimes with Users having trouble with Password Resets.

**Comment by DeveloperMetal** [comment]
> @forellana-digithinkit Does that make sense, or should I remove that feature too? This helps sometimes with Users having trouble with Password Resets.

Yeah, its fine to keep it I think so long a user with proper permissions (like website manager? or anyone more than just employee) are the only ones able to change it.

**Pull request merged**
