### PR TITLE
[v12] Update from upstream

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 1
           

Complexity increasing per file
==============================
- frappe/test_runner.py  3
- frappe/__init__.py  1
- frappe/contacts/doctype/contact/contact.js  1
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/contacts/doctype/address/address.js  2
- frappe/public/js/frappe/views/reports/report_view.js  2
         

Complexity decreasing per file
==============================
+ frappe/tests/test_form_load.py  -4
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 1
           

Complexity increasing per file
==============================
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/test_runner.py  3
- frappe/contacts/doctype/address/address.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/__init__.py  1
- frappe/contacts/doctype/contact/contact.js  1
         

Complexity decreasing per file
==============================
+ frappe/public/js/frappe/desk.js  -2
+ frappe/tests/test_form_load.py  -4
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 1
           

Complexity increasing per file
==============================
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/contacts/doctype/address/address.js  2
- frappe/contacts/doctype/contact/contact.js  1
- frappe/__init__.py  1
- frappe/test_runner.py  3
         

Complexity decreasing per file
==============================
+ frappe/tests/test_form_load.py  -4
+ frappe/public/js/frappe/desk.js  -2
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 1
           

Complexity increasing per file
==============================
- frappe/__init__.py  1
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/contacts/doctype/address/address.js  2
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/contacts/doctype/contact/contact.js  1
- frappe/test_runner.py  3
- frappe/core/doctype/data_import/exporter_new.py  2
         

Complexity decreasing per file
==============================
+ frappe/tests/test_form_load.py  -4
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/public/js/frappe/desk.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 1
           

Complexity increasing per file
==============================
- frappe/__init__.py  1
- frappe/contacts/doctype/contact/contact.js  1
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/test_runner.py  3
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/contacts/doctype/address/address.js  2
         

Complexity decreasing per file
==============================
+ frappe/public/js/frappe/desk.js  -2
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/tests/test_form_load.py  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 31
           

Complexity increasing per file
==============================
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/contacts/doctype/contact/contact.js  1
- frappe/contacts/doctype/address/address.js  2
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/test_runner.py  3
- frappe/__init__.py  1
- frappe/public/js/frappe/views/reports/report_view.js  2
         

Complexity decreasing per file
==============================
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/public/js/frappe/desk.js  -2
+ frappe/tests/test_form_load.py  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 31
           

Complexity increasing per file
==============================
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/contacts/doctype/address/address.js  2
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/test_runner.py  3
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/__init__.py  1
- frappe/contacts/doctype/contact/contact.js  1
         

Complexity decreasing per file
==============================
+ frappe/public/js/frappe/desk.js  -2
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/tests/test_form_load.py  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by DeveloperMetal** [comment]
@Alchez What's the difference on that conflict file? frappe/public/js/frappe/form/grid.js

Looks like a ```break``` is the only difference. Do you know why we have a break on ours?

**Comment by Alchez** [comment]
Oh, yeah, it was breaking some of our CSS while using some forms that had "Text" fields. Check this one: #191.

**Comment by DeveloperMetal** [comment]
@Alchez Also, what do you think of merging all of this and the other PR into a new test branch we can deploy and have a look first?

Lets get our CI pipeline setup for testing changes coming from upstream, what do you think?

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 31
           

Complexity increasing per file
==============================
- frappe/__init__.py  1
- frappe/test_runner.py  3
- frappe/contacts/doctype/contact/contact.js  1
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/contacts/doctype/address/address.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/public/js/frappe/data_import/import_preview.js  2
         

Complexity decreasing per file
==============================
+ frappe/tests/test_form_load.py  -4
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/public/js/frappe/desk.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by Alchez** [comment]
@forellana-digithinkit, agreed. I say we keep this branch for testing incoming features and fixes, and use `bloomstack-production` for stable deployments. We'd have to move over the server branches, but it seems better in the long run - less branches to manage too 😅

**Comment by DeveloperMetal** [comment]
@Alchez Awesome, sounds like a plan

Lets update production with what's on staging since this is what is going live right now and then we'll merge this stuff in.

We'll see about auto merging upstream changes automatically after this is done

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 31
           

Complexity increasing per file
==============================
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/__init__.py  1
- frappe/contacts/doctype/address/address.js  2
- frappe/test_runner.py  3
- frappe/contacts/doctype/contact/contact.js  1
- frappe/public/js/frappe/data_import/import_preview.js  2
         

Complexity decreasing per file
==============================
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/tests/test_form_load.py  -4
+ frappe/public/js/frappe/desk.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 31
           

Complexity increasing per file
==============================
- frappe/contacts/doctype/address/address.js  2
- frappe/__init__.py  1
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/test_runner.py  3
- frappe/contacts/doctype/contact/contact.js  1
- frappe/core/doctype/data_import/exporter_new.py  2
- frappe/public/js/frappe/views/reports/report_view.js  2
         

Complexity decreasing per file
==============================
+ frappe/tests/test_form_load.py  -4
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/public/js/frappe/desk.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 31
           

Complexity increasing per file
==============================
- frappe/contacts/doctype/contact/contact.js  1
- frappe/contacts/doctype/address/address.js  2
- frappe/__init__.py  1
- frappe/public/js/frappe/data_import/import_preview.js  2
- frappe/test_runner.py  3
- frappe/public/js/frappe/views/reports/report_view.js  2
- frappe/core/doctype/data_import/exporter_new.py  2
         

Complexity decreasing per file
==============================
+ frappe/public/js/frappe/desk.js  -2
+ frappe/integrations/doctype/slack_webhook_url/slack_webhook_url.py  -1
+ frappe/tests/test_form_load.py  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=5041355&bid=16601230)

**Pull request merged**
