### PR TITLE
fix: timezone fixes

### PR DESCRIPTION
**Pull request by hrwX**
- The system only displays time form one timezone and it messes up for a user in another timezone.
- This becomes pretty evident in case of setting datetime in sensitive documents.

### CODE REVIEW

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Comment by neilLasrado** [comment]
@hrwX whats going on with this PR?

**Comment by hrwX** [comment]
> @hrwX whats going on with this PR?

Damini did a bit of testing, found other issues related to dynamically showing time as per timezone. Later got caught up in the imp stuff. Will fix this soon

**Comment by hrwX** [comment]
@sahil28297 create instance

**Comment by sahil28297** [comment]
@dti-deploy destroy instance

**Comment by sahil28297** [comment]
@dti-deploy create instance

**Comment by sahil28297** [comment]
@dti-deploy create instance

**Comment by sahil28297** [comment]
@dti-deploy create instance

**Comment by sahil28297** [comment]
@dti-deploy create instance

**Comment by sahil28297** [comment]
@dti-deploy create instance

**Comment by sahil28297** [comment]
@dti-deploy destroy instance

**Comment by DeveloperMetal** [comment]
@hrwX @sahil28297 what's the status on this?

**Pull request closed without merging**
