### PR TITLE
Added options api for login pre flight requests

### PR DESCRIPTION
**Pull request by vigilantee**
> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by Alchez** [comment]
@vigilantee, what is this change exactly? Can you add some context and description please?

**Comment by DeveloperMetal** [comment]
@Alchez I believe this is for CORs preflight check. It allows another domain to reach the server...

@vigilantee This really needs more thought, that will open up the domain to handle calls from any domain. It defeats the purpose of CORs. We should be checking against a domain whitelist and not allowing any domain in...

**Comment by vigilantee** [comment]
@DeveloperMetal Yeah true.
@Alchez I think we should drop this PR for now.

**Comment by Alchez** [comment]
@vigilantee, alright, closing this one

**Pull request closed without merging**
