### PR TITLE
feat: cubejs integration in admin_insights page

### PR DESCRIPTION
**Pull request by vigilantee**
For cube JS integration in admin_insight page.
https://bloomstack.com/desk#Form/Task/TASK-2020-01972

### CODE REVIEW

**Comment by neilLasrado** [comment]
@vigilantee Can you please resolve the merge conflicts and push?

**Review by DeveloperMetal — COMMENTED** [review]
I don't understand this PR

Half of the code here is for Chat clietn and the other half for the tree view. How is any of this related to Cubejs integration?

**Comment by neilLasrado** [comment]
@vigilantee can you please clarify what's going on here?

**Comment by hrwX** [comment]
@vigilantee Can you update the status of the PR ?? Its been open for a long time, if not could you please close this

**Comment by neilLasrado** [comment]
@vigilantee can you please update this PR?

**Comment by vigilantee** [comment]
Opening a new PR for dissociating chat js @neilLasrado  I guess the chat JS changes are reflecting for some reason which shouldn't happen.

**Comment by vigilantee** [comment]
Not Required as the changes are already present since the merge of a different PR for cube JS. We can close it @hrwX

**Pull request closed without merging**
