### PR TITLE
feat: allow forming JSON requests in webhook

### PR DESCRIPTION
**Pull request by Alchez**
**Screenshots / GIFs:**

image

comment-webhook

### CODE REVIEW

**Comment by vjFaLk** [comment]
Upstream?

Also 😘

**Comment by Alchez** [comment]
Waiting on reviews, I'll put it up when its approved. Don't wanna keep adding changes in multiple places :sweat_smile:

**Comment by vjFaLk** [comment]
What do you mean? You only need to make __four__ PRs!? What's the big deal? 

/s

**Comment by revant** [comment]
Everything looks good.

Can this be setup on any server preferably corp garden @vjFaLk 

@prafful1234 can verify if nothing breaks for support portal.

**Review by vjFaLk — APPROVED** [review]

**Comment by Alchez** [comment]
Made upstream to [v11](https://github.com/frappe/frappe/pull/8263) and [develop](https://github.com/frappe/frappe/pull/8264).

**Pull request merged**
