### PR TITLE
fix(report): Disable duplicate Address and Contacts report

### PR DESCRIPTION
**Pull request by Alchez**
Duplicate of https://delta9.bloomstack.com/desk#Form/Report/Address%20And%20Contacts.

### CODE REVIEW

**Comment by vjFaLk** [comment]
Disable the other one that we're replacing as well?

**Comment by Alchez** [comment]
That's in ERPNext. I don't think it'll be a problem since we've changed it from an ERPN module to a D9 module.

**Comment by vjFaLk** [comment]
That sounds like even more of a problem?! We'll end up with two reports with the same name. Or am I not understanding this correctly?

**Comment by Alchez** [comment]
Honestly, not sure how this works either. After I changed the module to D9, there was only one report that was showing up in the search results. Since only one report can exist with that name, I'm guessing ERPN handles it accordingly (maybe based on apps order?).

Let's merge and see how it does, and then we can disable the ERPN report explicitly if there's two of them.

**Comment by vjFaLk** [comment]
image

This is from the Tugboat image here - https://github.com/DigiThinkIT/delta9/pull/111

One is from ERPNext and the other from Delta9

**Comment by Alchez** [comment]
Hm, I'll add a disable in ERPN then. Cause I see 3 reports on that Tugboat instance.

image

**Comment by vjFaLk** [comment]
LOL

**Comment by Alchez** [comment]
Disabled the other report at https://github.com/DigiThinkIT/erpnext/pull/158.

**Comment by vjFaLk** [comment]
This should be disabled via ERPNext, as part of the after_install hooks maybe? Just see if they're doing something similar to this.

**Comment by Alchez** [comment]
We already have an `after_install` hook in D9. I can add it to that.

**Comment by Alchez** [comment]
Added patch and install hook at https://github.com/DigiThinkIT/delta9/pull/111.

**Pull request closed without merging**
