### PR TITLE
feat: on clearing image attachment, remove attached file

### PR DESCRIPTION
**Pull request by vishdha**
https://digithinkit.global/desk#Form/Task/TASK-2019-00793

 on image clear attachment event remove attach file
Before:
image1

After:
image2

depends on for employee https://github.com/DigiThinkIT/erpnext/pull/266

### CODE REVIEW

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/mail_67/frappe/pullRequest?prid=4663554&bid=15612922)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/mail_67/frappe/pullRequest?prid=4663554&bid=15612922)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/mail_67/frappe/pullRequest?prid=4663554&bid=15612922)

**Review by Alchez — APPROVED** [review]

**Comment by vishdha** [comment]
for hotfix: https://github.com/frappe/frappe/pull/9068
for pre relase https://github.com/frappe/frappe/pull/9069

**Review by Alchez — APPROVED** [review]

**Pull request merged**
