### PR TITLE
Remove mandatory email requirement in Auto Email Report

### PR DESCRIPTION
**Pull request by Alchez**
Fixes https://github.com/DigiThinkIT/bloomstack/issues/292.

### CODE REVIEW

**Comment by vjFaLk** [comment]
If this is not going back to Frappe then don't change this in Frappe. Hook it in.

**Comment by Alchez** [comment]
But, but I asked you in chat, and you said it's fine.

Also, how do I hook this specific function? It's inside a class.

**Comment by vjFaLk** [comment]
> But, but I asked you in chat, and you said it's fine.
> 
> Also, how do I hook this specific function? It's inside a class.

er. I might have missed that. Add the validation in JS and hook that in?

**Comment by Alchez** [comment]
There's multiple entry points for sending out the report, including daily and monthly hooks. I can override the button maybe, but it'll still fail when it gets no recipients from the hook.

**Comment by vjFaLk** [comment]
Ya know what? Can you send this as a PR to Upstream and mention the use case? Tell that that we plan to do it **properly** soon as well. I'll merge this here for now.

**Review by vjFaLk — APPROVED** [review]

**Pull request merged**
