### PR TITLE
chore: port dashboards to v12

### PR DESCRIPTION
**Pull request by hrwX**
- Port v13 dashboards to v12
- [ported from](https://github.com/frappe/frappe/pull/9518)
- [Asana](https://app.asana.com/0/1198992588740629/1198180273146130)
    - image
    - image

### CODE REVIEW

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Comment by sahil28297** [comment]
@sahil28297 create instance

**Review by sahil28297 — APPROVED** [review]

**Comment by hrwX** [comment]
@sahil28297 destroy instance

**Comment by sahil28297** [comment]
@sahil28297 destroy instance

**Pull request merged**
