### PR TITLE
feat: add security headers to webhook

### PR DESCRIPTION
**Pull request by Alchez**
image

### CODE REVIEW

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- frappe/integrations/doctype/webhook/webhook.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=4807611&bid=15993847)

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/frappe/pull/9244).

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- frappe/integrations/doctype/webhook/webhook.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=4807611&bid=15993847)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- frappe/integrations/doctype/webhook/webhook.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mail_67/frappe/pullRequest?prid=4807611&bid=15993847)

**Review by revant — APPROVED** [review]

**Pull request merged**
